pandoc .\lab1.md --pdf-engine=xelatex --filter pandoc-xnos --standalone --template=eisvogel.tex --mathjax -N -o lab1.pdf
pandoc .\lab2.md --pdf-engine=xelatex --filter pandoc-xnos --standalone --template=eisvogel.tex --mathjax -N -o lab2.pdf
pandoc .\lab3.md --pdf-engine=xelatex --filter pandoc-xnos --standalone --template=eisvogel.tex --mathjax -N -o lab3.pdf
pandoc .\lab4.md --pdf-engine=xelatex --filter pandoc-xnos --standalone --template=eisvogel.tex --mathjax -N -o lab4.pdf
pandoc .\lab5.md --pdf-engine=xelatex --filter pandoc-xnos --standalone --template=eisvogel.tex --mathjax -N -o lab5.pdf
pandoc .\lab6.md --pdf-engine=xelatex --filter pandoc-xnos --standalone --template=eisvogel.tex --mathjax -N -o lab6.pdf
pandoc .\lab7.md --pdf-engine=xelatex --filter pandoc-xnos --standalone --template=eisvogel.tex --mathjax -N -o lab7.pdf
pandoc .\lab8.md --pdf-engine=xelatex --filter pandoc-xnos --standalone --template=eisvogel.tex --mathjax -N -o lab8.pdf
pandoc .\lab9.md --pdf-engine=xelatex --filter pandoc-xnos --standalone --template=eisvogel.tex --mathjax -N -o lab9.pdf
pandoc .\lab10.md --pdf-engine=xelatex --filter pandoc-xnos --standalone --template=eisvogel.tex --mathjax -N -o lab10.pdf
pandoc .\lsa1.md --pdf-engine=xelatex --filter pandoc-xnos --standalone --template=eisvogel.tex --mathjax -N -o lsa1.pdf
pandoc .\lsa2.md --pdf-engine=xelatex --filter pandoc-xnos --standalone --template=eisvogel.tex --mathjax -N -o lsa2.pdf